// ==========================================
// DB 1: FUNDAMENTOS (TÓPICOS 2 AO 5)
// Meta: 140 Tópicos rigorosamente estruturados
// ==========================================

const db_fundamentos = {
    // Tópico 2: Análise Profunda / Fisiopatologia / Epidemiologia (30 Tópicos)
    sec_2: {
        title: "2. Análise Profunda e Meticulosa 🔬",
        list: [
            "1. 🌍 Epidemiologia: AVC é a 2ª principal causa de morte e a 1ª de incapacidade global.",
            "2. 🫀 Etiologia TOAST 1: Aterosclerose de grandes vasos (Trombos brancos ricos em plaquetas).",
            "3. ❤️ Etiologia TOAST 2: Cardioembolismo (Fibrilação Atrial é o principal fator, coágulos vermelhos).",
            "4. 🧠 Etiologia TOAST 3: Oclusão de pequenos vasos (Lacunar, lipohialinose crônica).",
            "5. 🩸 Etiologia TOAST 4: Outras causas (Dissecção arterial, vasculites, estados de hipercoagulabilidade).",
            "6. ❓ Etiologia TOAST 5: Criptogênico (Indeterminado após investigação exaustiva, ESUS).",
            "7. 📉 Fatores de Risco (Modificáveis Graves): Hipertensão Arterial Sistêmica (HAS) e Diabetes Mellitus (DM).",
            "8. 🚬 Fatores de Risco (Modificáveis de Estilo de Vida): Tabagismo, Sedentarismo, Obesidade, Etilismo.",
            "9. 🧬 Fatores de Risco (Não Modificáveis): Idade avançada, Sexo masculino, Etnia negra, Histórico familiar.",
            "10. ⚡ Fisiopatologia (O Início): Oclusão aguda cessa o fluxo, gerando o Core Isquêmico (tecido morto).",
            "11. 🎯 O Alvo do Tratamento: Penumbra isquêmica (tecido viável adjacente, mas eletricamente silencioso e hipoperfundido).",
            "12. ⚡ Falha da Bomba: A falta de ATP desativa a bomba Na+/K+ ATPase neuronal em minutos.",
            "13. 🌊 Edema Citotóxico: Influxo passivo e maciço de Sódio, que arrasta água para dentro da célula.",
            "14. 🔥 Excitotoxicidade: Células mortas liberam Glutamato letal na fenda sináptica.",
            "15. 💀 Receptores NMDA: Glutamato ativa esses canais, forçando um influxo brutal de Cálcio (Ca++) na Penumbra.",
            "16. 🧨 Destruição Celular: O Ca++ hiperativa endonucleases, proteases e NOS (Óxido Nítrico), destruindo o citoesqueleto.",
            "17. 📉 Vasoparalisia: A área de penumbra perde a autorregulação cerebral e não consegue mais fazer vasoconstrição/vasodilatação reflexa.",
            "18. 🩸 Fluxo Passivo: Na penumbra, o Fluxo Sanguíneo Cerebral torna-se linearmente dependente da Pressão Arterial Média (PAM).",
            "19. ⏳ Apoptose: Horas após o evento primário, células da penumbra morrem por apoptose ativada por danos no DNA.",
            "20. 🧠 Edema Vasogênico: Ocorre mais tarde (3 a 5 dias), envolvendo quebra da Barreira Hematoencefálica (BHE).",
            "21. 🚨 AVC Maligno: O inchaço cerebral atinge o pico (72-96h), causando shift de linha média e herniação fatal.",
            "22. 🛡️ Prevenção Primária (Metas): Controle estrito da PA (< 130/80 em pacientes de alto risco aterosclerótico).",
            "23. 💊 Prevenção Primária (Glicose): Controle estrito de DM com HbA1c < 7%.",
            "24. 🩸 Prevenção Secundária (AAS): Uso imediato de antiplaquetários para evitar recorrência precoce (exceto se trombolisado < 24h).",
            "25. ❤️ Prevenção Secundária (Anticoagulação): Mandatória em fibrilação atrial não valvar guiada pelo CHA2DS2-VASc.",
            "26. 📉 Estatinas: Efeito pleiotrópico anti-inflamatório além do hipolipemiante. LDL alvo < 70 (ou até < 55).",
            "27. 🔪 Intervenção Carotídea: Endarterectomia se estenose carotídea ipsilateral sintomática > 70% (e às vezes > 50%).",
            "28. 🔄 Comorbidades Relacionadas: Insuficiência Cardíaca, apneia obstrutiva do sono, doença renal crônica.",
            "29. 🧬 Fisiopatologia Hemorrágica Associada: A revascularização súbita de vasos necrosados gera transformação hemorrágica.",
            "30. 🛡️ Neuroproteção: Fatores inerentes (rede vascular de colaterais, polígono de Willis integro) são os maiores protetores naturais contra extensão do Core."
        ]
    },

    // Tópico 3: Análise Dirimida (30 Tópicos)
    sec_3: {
        title: "3. Análise Dirimida Substitutiva (UpToDate/AHA) 📖",
        list: [
            "1. ⏱️ Tempo é Cérebro: O dogma central de todo protocolo. 1.9 milhões de neurônios morrem por minuto em uma LVO.",
            "2. 🚨 Triagem Rápida: Uso do Cincinnati ou FAST na cena pré-hospitalar para desviar do hospital errado.",
            "3. 🩸 Avaliação Inicial: Coleta de HGT imediata. Hipoglicemia < 60 mg/dL é o maior mimic tratável.",
            "4. 🧠 Tomografia Sem Contraste (NCCT): Exame inicial DE OURO. Não é para ver o isquêmico, mas sim para descartar qualquer foco hemorrágico intracraniano.",
            "5. 🧮 Escala NIHSS: Avaliação quantitativa da gravidade (0 a 42). Valores > 6 sugerem LVO.",
            "6. ⏰ Janela Terapêutica (Alteplase): Padrão Ouro é administração EV em até 4,5 horas do Last Seen Normal.",
            "7. 💉 Trombolítico Ouro: Alteplase (rt-PA). Quebra o coágulo ativando o plasminogênio. Tem meia-vida curta.",
            "8. 🎯 Meta Pressórica Pré-Alteplase: Extremamente rígida. PA DEVE estar ≤ 185/110 mmHg para não sangrar o cérebro.",
            "9. 🎯 Meta Pressórica Pós-Alteplase: PA DEVE manter-se < 180/105 mmHg pelas próximas 24 horas.",
            "10. ⚡ Trombectomia Mecânica (TM): Cateterismo cerebral para remover fisicamente o coágulo. Focado em Oclusão de Grande Vaso (LVO).",
            "11. ⏰ Janela de Trombectomia (Inicial): Até 6 horas sem necessidade de exames de imagem avançados (apenas TC/Angio-TC).",
            "12. ⏰ Janela de Trombectomia Estendida: De 6 até 24 horas.",
            "13. 🖼️ Pré-requisito para Trombectomia 24h: Imagem de Perfusão (CTP ou RM) provando Mismatch Volumétrico (Core pequeno vs Penumbra GIGANTE).",
            "14. 🛌 Wake-Up Stroke: Se não souber a hora do AVC, usa-se a RM. Se brilhar no DWI e NÃO brilhar no FLAIR, ocorreu há < 4,5h.",
            "15. 🚫 Manejo Sem Reperfusão: Se perdeu a janela, a PA será mantida livre até impressionantes 220/120 mmHg (Hipertensão Permissiva).",
            "16. 💊 Anticoagulantes/AAS: Absolutamente contraindicados nas primeiras 24h após trombolítico (sob risco de hemorragia maciça).",
            "17. 🌡️ Alvo de Temperatura: Normotermia induzida rigorosa (Acetaminofeno). Febre causa dano secundário imediato.",
            "18. 🍭 Alvo Glicêmico: 140 a 180 mg/dL. Hipoglicemia e normoglicemia estrita (Trial SHINE) pioram prognóstico.",
            "19. 🌬️ Alvo de Oxigênio: Apenas manter SpO2 > 94%. O2 em normoxêmicos só gera espécias reativas e radicais livres.",
            "20. 🛌 Posicionamento: Manter em 0° se hipoperfundido ou instável. Se ok, 30° previne aspiração pulmonar e ajuda no dreno venoso.",
            "21. 🍽️ Via Oral Segura (Fono): Dieta zero (NPO) rigorosa na emergência até teste de engasgo/deglutição à beira leito.",
            "22. 🩸 Drip and Ship: NUNCA atrasar a trombólise na UPA esperando ambulância para transferir à Hemodinâmica. Trombolise primeiro.",
            "23. 🧠 AVC Menor (Minor Stroke): Se déficit for muito leve e NÃO incapacitante (Ex: só anestesia nos dedos), NÃO se recomenda Alteplase.",
            "24. 💊 DAPT: Para AVC Menor (NIHSS ≤ 3) não trombolisado, usar Dupla Antiagregação (AAS + Clopidogrel) por 21 dias.",
            "25. 📉 Profilaxia DVT/TVP: Compressão pneumática intermitente. Profilaxia farmacológica retida por 24h se rt-PA.",
            "26. 🧪 Avaliação Laboratorial: Apenas o HGT é obrgatório atrasar o rt-PA. Só aguardar TAP/TTPa/Plaquetas se paciente tiver histórico de uso, câncer ou coagulopatia.",
            "27. 🏥 O Papel das Stroke Units: Monitorização contínua de NIHSS por enfermeiros especializados reduz mortalidade em até 20%.",
            "28. 🧠 Imagem Complementar: Angio-TC (CTA) na sala de emergência ajuda a mapear LVO, mas se houver atraso na máquina, não segure a Alteplase.",
            "29. 🛡️ Neuroproteção (Falha Histórica): Nenhuma droga provou proteger os neurônios isoladamente no mercado, o foco é REPERFUSÃO.",
            "30. 🚑 Triagem de Retaguarda: Acesso venoso central NÃO é indicado na fase aguda (risco de sangramento se puncionar mal artéria pré-trombólise). Dois AVP calibrosos são a regra."
        ]
    },

    // Tópico 4: Tópicos a Memorizar (50 Tópicos numéricos brutos para TEMI)
    sec_4: {
        title: "4. Tópicos Clássicos a Memorizar (Gabarito TEMI) ✅",
        list: [
            "1. Dose de Alteplase (rt-PA): 0,9 mg/kg.",
            "2. Dose Máxima de Alteplase: 90 mg (mesmo se o paciente pesar 120 kg).",
            "3. Velocidade Bolus rt-PA: 10% da dose total administrada ao longo de 1 minuto.",
            "4. Velocidade Bomba rt-PA: Os 90% restantes em infusão contínua em 1 hora.",
            "5. Dose de Tenecteplase (TNK): 0,25 mg/kg.",
            "6. Dose Máxima de TNK: 25 mg.",
            "7. Velocidade TNK: Bolus rápido e único (5 a 10 segundos).",
            "8. Meta PA Pré-Trombólise: Menor ou igual a 185/110 mmHg.",
            "9. Meta PA Pós-Trombólise (Fase aguda): Menor ou igual a 180/105 mmHg por 24h.",
            "10. Meta PA Conservadora (Sem Trombólise): Menor que 220/120 mmHg.",
            "11. Janela Terapêutica Trombólise: 0 a 4,5 horas.",
            "12. Janela Terapêutica Trombectomia Ouro: 0 a 6 horas.",
            "13. Janela Estendida Trombectomia (Mismatch): 6 a 24 horas.",
            "14. Glicemia pré-trombolítico: Deve estar acima de 50 mg/dL (preferencialmente >60).",
            "15. Glicemia alvo UTI: 140 a 180 mg/dL.",
            "16. Temperatura alvo: Menor que 37,5°C (Normotermia).",
            "17. Plaquetas contraindicação rt-PA: < 100.000 /mm3.",
            "18. RNI contraindicação rt-PA: > 1,7.",
            "19. TTPa elevado: Contraindica rt-PA se alterado além da normalidade.",
            "20. Uso de NOAC (Eliquis/Xarelto): Contraindica rt-PA se última dose foi a < 48h.",
            "21. TC com Hemorragia Subaracnóide ou Intraparenquimatosa: Contraindicação ABSOLUTA a rt-PA.",
            "22. Cirurgia Intracraniana ou Espinhal: Contraindicação absoluta em 3 meses.",
            "23. Histórico de AVC Isquêmico prévio: Contraindica se ocorreu nos últimos 3 meses.",
            "24. Traumatismo Craniano Grave recente: Contraindica em 3 meses.",
            "25. Infarto Miocárdico (IAM): Contraindica relativo/absoluto (Depende do Guideline se < 3 meses e complicado).",
            "26. Sangramento Gastrointestinal Ativo: Contraindicação em 21 dias.",
            "27. Labetalol Bolus Inicial: 10 a 20 mg em 1-2 minutos.",
            "28. Nicardipina Bomba Inicial: 5 mg/hora, titulada até controle.",
            "29. Droga Reversora do Alteplase (Empírica): Crioprecipitado (Rico em Fator VIII e Fibrinogênio) ou Ácido Tranexâmico.",
            "30. Reversor específico da Dabigatrana: Idarucizumabe (Praxbind).",
            "31. Reversor específico dos Anti-Xa (Rivaroxabana/Apixabana): Andexanet Alfa.",
            "32. Dose Padrão AAS aguda: 160 a 300 mg (após as 24h cegas do rt-PA).",
            "33. Frequência aferição PA no rt-PA: A cada 15 min nas primeiras 2h, depois a cada 30 min por 6h, depois de hora em hora.",
            "34. Piora de Neurologia (NIHSS cai 4 pts): SINAL VERMELHO - Parar infusão do rt-PA e correr para a TC s/ contraste urgente (Sangrou).",
            "35. Critério Mismatch: Quando a lesão vista na perfusão (tecido sofrendo) é muito MAIOR que a lesão de core (tecido já morto).",
            "36. Escore ASPECTS Tomográfico: Avalia 10 territórios da ACM. Se pontuação ≤ 5, significa infarto imenso (> 1/3 do hemisfério).",
            "37. Edema no AVC: Pode simular neoplasia na fase subaguda. Não confundir na RM.",
            "38. Escala mRS (Rankin Modificada): Mede desfecho funcional. mRS 0-2 = Bom desfecho funcional (independente). mRS 6 = Morte.",
            "39. Duração ideal de DAPT em AVC Menor/AIT Alto Risco: 21 dias (Estudos CHANCE/POINT).",
            "40. Artéria Cerebral Média: Dá origem aos ramos lenticuloestriados (comuns em AVCs lacunares hipertensivos profundos).",
            "41. Artéria Cerebral Anterior: Sua oclusão afeta mais o membro inferior do que o superior e gera mutismo acinético/alterações psiquiátricas.",
            "42. Artéria Cerebral Posterior: Sua oclusão gera hemianopsia homônima com preservação macular e, às vezes, dor talâmica intratável (Dejerine-Roussy).",
            "43. Artéria Basilar: Oclusão gera Síndrome Locked-In ou morte rápida por isquemia de ponte/bulbo.",
            "44. Punção Lombar recente: Contraindicação relativa para trombólise se dentro de 7 dias (difícil compressão de sangramento espinhal).",
            "45. Trombólise intra-arterial de resgate: Opção até 6h se TM falhar (via cateterismo).",
            "46. Angioedema Orofacial associado ao rt-PA: É uma complicação rara e fatal; mais comum em pacientes que usam iECA. Tratar com corticoide/adrenalina.",
            "47. Manejo Pressórico Lento (Conservador): Para pacientes SEM indicação de reperfusão, reduzir a PA apenas 15% nas primeiras 24 horas se > 220/120.",
            "48. Nitroprussiato de Sódio: DROGA PROIBIDA para AVC Agudo, pois causa severa vasodilatação cerebral (aumenta muito a PIC e zera a PPC).",
            "49. Manitol/Salina Hipertônica: Apenas na fase tardia (dia 3-5) se sinais francos de herniação por edema cerebral. Inútil no dia 1.",
            "50. Critérios de indicação para Craniectomia: Infarto de MCA total, desvio de linha média > 5mm, rebaixamento rápido de consciência, e idade idealmente < 60 anos."
        ]
    },

    // Tópico 5: Atualizações (30 Tópicos)
    sec_5: {
        title: "5. Principais Atualizações (AHA / Ensaios) 📊",
        list: [
            "1. AHA 2023 Guidelines: TNK (Tenecteplase) entra como recomendação classe I/IIa, preferencial ao Alteplase em cenários de Bridging (fazer antes de TM).",
            "2. DAWN Trial: Demonstrou o gigantesco benefício funcional da Trombectomia entre 6 e 24h para grandes mismatch clínicos-radiológicos.",
            "3. DEFUSE-3 Trial: Demonstrou sucesso semelhante da TM para pacientes com base estrita no volume de penumbra calculado via RM/CTP (RAPID software).",
            "4. WAKE-UP Trial: Permitiu a trombólise venosa baseada no 'relógio do tecido' usando RM (DWI+/FLAIR-) em vez do relógio do relógio de parede.",
            "5. EXTEND Trial: Abriu espaço para trombolisar até 9h (ou wake-up) baseando-se no mismatch de perfusão. (Não amplamente adotado como rotina padrão frente à Trombectomia, mas válido).",
            "6. SHINE Trial: A insulina agressiva em bomba não funcionou. O controle frouxo (140-180 mg/dL) com dose SC é o vencedor, provando que cérebro grave não suporta hipoglicemia leve.",
            "7. BP-TARGET Trial: Após TM com sucesso completo (reperfusão TICI 2b-3), tentou-se abaixar a PA intensamente (< 130 mmHg) para evitar hemorragia. Falhou. Não reduziu hemorragia e pode causar mais isquemia residual.",
            "8. RESCUE-Japan Limit Trial: Provou que pacientes com 'cores' isquêmicos já grandes (ASPECTS 3-5) ainda têm excelente benefício de recuperação neurológica com a Trombectomia Mecânica (quebrou o paradigma de que só ASPECTS > 6 podia fazer).",
            "9. SELECT2 Trial: Confirmou o achado do RESCUE, endossando Trombectomia segura em grandes territórios infartados (grandes cores não contraindicam TM isoladamente hoje).",
            "10. BAOCHE Trial: Abordou especificamente oclusões assassinas da Artéria Basilar e mostrou que TM em janela de até 24h reduziu mortes dramaticamente na circulação posterior.",
            "11. ATTENTION Trial: Corroborou fortemente os dados do BAOCHE na Trombectomia em circulação posterior estendida.",
            "12. CHANCE Trial: Dupla antiagregação (AAS+Clopidogrel) nas primeiras 24h reduz chance de recorrência massivamente para o subgrupo TIA / Minor Stroke, mantida por 21 dias.",
            "13. POINT Trial: Reafirmou o estudo CHANCE em populações americanas. A janela da dupla é curta, usar DAPT > 90 dias só aumenta sangramento sem benefício.",
            "14. PRISMS Trial: Avaliou Trombolítico vs Aspirina nos AVCs menores não-incapacitantes (NIHSS ≤ 5). Resultado: Alteplase não superou o AAS, mas aumentou o risco de sangrar. Portanto, NÃO trombolisamos déficits sutis sem incapacidade.",
            "15. ESCAPE-NA1 Trial: O mais inovador (Fármacos). O Nerinetida inibiu a morte celular bloqueando receptores NMDA-NO. Reduziu os infartos espetacularmente em animais e humanos submetidos a TM sem alteplase. Porém, em associação com Alteplase o efeito sumiu (interação química com a plasmina).",
            "16. ANGIO-TC RÁPIDA: Hoje, AHA exige que a Angio-TC seja feita no mesmo pacote da TC Sem Contraste para acelerar a decisão da sala de hemodinâmica.",
            "17. Mobile Stroke Units (Ambulâncias com Tomografia): Trials mostraram que as MSUs entregam a trombólise em média 35 a 40 minutos mais rápido que o atendimento hospitalar normal. Salva bilhões de neurônios.",
            "18. IA de Perfusão (ex: Viz.ai e RAPID): Softwares de inteligência artificial automatizaram o cálculo de Mismatch do DEFUSE-3 enviando um SMS automático para o celular do neurocirurgião se houver core pequeno e penumbra grande.",
            "19. Terapia Celular (Células Tronco): Estudos fase II (ex: MASTERS-2) testam infusão de células derivadas da medula óssea para neuroreparo inflamatório após 48h.",
            "20. Anticoagulação no 'Embolic Stroke of Undetermined Source' (ESUS): Os trials NAVIGATE-ESUS (Rivaroxabana) e RESPECT-ESUS (Dabigatrana) tentaram provar que NOACs protegem contra AVCs sem fonte óbvia (placas aórticas ou arritmia subclínica). Ambos falharam. Continua valendo AAS.",
            "21. Fechamento de FOP (Forame Oval Patente): Ensaios (RESPECT, CLOSE, REDUCE) aprovaram de vez o fechamento percutâneo do FOP em jovens (< 60a) com AVC isquêmico sem outra causa identificada.",
            "22. Novos Reversos NOAC: Andexanet Alfa é super restrito no SUS, mas entra no Guideline AHA como padrão ouro se houver hemorragia cerebral ou necessidade de trombólise emergencial após uso de Apixabana/Rivaroxabana.",
            "23. Monitor de Loop Implantável (ILR): A AHA aumentou o grau de recomendação de colocar chips de gravação cardíaca subcutâneos nos pacientes pós AVC de causa duvidosa para descobrir fibrilação atrial oculta tardia (monitorizar por até 3 anos).",
            "24. Suspensão de Estatinas no Hemorrágico: Reafirmado que iniciar Estatina precoce PÓS Hemorrágico pode agravar resangramentos (ao contrário do Isquêmico, onde a estatina salva vidas).",
            "25. Desuso da Heparina Contínua: AHA reforça que heparinação plena empírica no infarto isquêmico agudo não tem benefício profilático ou terapêutico agudo que supere o gigantesco risco de transformação hemorrágica petequial e lobar.",
            "26. Avaliação de Colaterais (Score Tan): Agora radiologistas reportam a graduação de circulação colateral via Leptomeníngeas, sendo definidor auxiliar da rapidez da necrose. Paciente com boa colateral aguenta janela estendida muito mais facilmente.",
            "27. Tempo Door-To-Needle Metas Apertadas: AHA propôs baixar a meta para centros avançados: Antes era < 60 min, agora a recomendação máxima diz que > 50% dos pacientes devem receber a agulha em menos de 45 minutos da porta, idealmente < 30min.",
            "28. Door-In-Door-Out (DIDO) em Drip and Ship: O tempo na emergência da UPA primária não deve passar de 120 minutos entre entrar, fazer TC, trombolisar e transferir de ambulância para a trombectomia.",
            "29. Inserção do conceito 'First Pass Effect': Na trombectomia, focar as técnicas em puxar e limpar 100% da artéria na PRIMEIRA passagem do Stent-Retriever. A cada nova passada do cateter o risco endotelial e embolia distal aumenta severamente.",
            "30. Uso de Balão de Oclusão (BGC): Trombectomia tem agora maior chance de recanalização perfeita se for associada à insuflação de um balão no pescoço para impedir o fluxo sanguíneo anterógrado enquanto o cirurgião arrasta o coágulo de volta (evita que pedaços do coágulo subam)."
        ]
    }
};
