
const SUPPORT_OPTIONS = ["Ar ambiente","CN O2","Máscara simples","Venturi","MR","CBAF/HFNC","VNI/CPAP/BiPAP","VM invasiva","TQT/VM","ECMO"];
const MODE_OPTIONS = ["VCV","PCV","PRVC","SIMV-VC","SIMV-PC","PSV","CPAP","BiPAP/VNI","APRV/BiLevel","ASV","NAVA/PAV","CBAF/HFNC"];
const DEMO_CASES = {
  "Manual": {},
  "SARA grave — VM protetora difícil": {age:56,sex:"Masculino",height_cm:170,weight_kg:86,support:"VM invasiva",vent_mode:"VCV",hypercapnia_risk:false,ards_suspected:true,acute_onset:true,bilateral_opacities:true,noncardiogenic_edema:true,spo2:88,rr:30,hr:118,sbp:95,high_wob:true,shock:false,ph:7.22,paco2:58,pao2:62,hco3:22,be:-5,lactate:3.2,sao2:88,fio2:.80,vt_ml:480,peep:14,pplat:32,ppeak:40,pinsp:18,pexp:14,ti:.8,te:1.2,flow_l_min:65,map_cmH2O:20},
  "DPOC exacerbado — VNI": {age:72,sex:"Feminino",height_cm:158,weight_kg:62,support:"VNI/CPAP/BiPAP",vent_mode:"BiPAP/VNI",hypercapnia_risk:true,ards_suspected:false,acute_onset:true,bilateral_opacities:false,noncardiogenic_edema:false,spo2:90,rr:32,hr:105,sbp:130,high_wob:true,shock:false,ph:7.27,paco2:72,pao2:62,hco3:32,be:5,lactate:1.6,sao2:90,fio2:.35,vt_ml:420,peep:6,pplat:0,ppeak:18,pinsp:12,pexp:6,ti:.9,te:1,flow_l_min:40,map_cmH2O:10},
  "CBAF falhando — hipoxemia": {age:64,sex:"Masculino",height_cm:175,weight_kg:88,support:"CBAF/HFNC",vent_mode:"CBAF/HFNC",hypercapnia_risk:false,ards_suspected:true,acute_onset:true,bilateral_opacities:true,noncardiogenic_edema:true,spo2:86,rr:34,hr:122,sbp:102,high_wob:true,shock:false,ph:7.44,paco2:31,pao2:58,hco3:21,be:-2,lactate:2.4,sao2:86,fio2:.90,vt_ml:0,peep:0,pplat:0,ppeak:0,pinsp:0,pexp:0,ti:.9,te:.9,flow_l_min:60,map_cmH2O:0}
};
const OXYGEN_DEVICES = [
 ["Cateter nasal O₂ (CN O₂)","1–6 L/min","24–44%","Hipoxemia leve; FiO₂ variável, depende do padrão ventilatório.","Fluxos altos ressecam; não controla FiO₂ com precisão."],
 ["Máscara simples","6–10 L/min","28–50%","Necessidade intermediária de O₂ sem controle fino de FiO₂.","Evitar fluxo <5–6 L/min pelo risco de reinalação de CO₂."],
 ["Máscara de Venturi","4–15 L/min conforme adaptador","24–50/60%","DPOC/risco hipercápnico quando FiO₂ controlada é desejada.","Ajustes dependem do fabricante; conferir adaptador e fluxo total."],
 ["Máscara com reservatório (MR)","10–15+ L/min","60–90%","Ponte para suporte avançado em hipoxemia importante.","Reservatório deve permanecer inflado; não reduz trabalho respiratório."],
 ["CBAF / HFNC","20–60/70 L/min","21–100%","Falência hipoxêmica com necessidade de alto fluxo e lavagem de espaço morto.","Monitorar ROX/tendência; evitar atraso de intubação se falha."],
 ["VNI CPAP/BiPAP","Depende do ventilador/interface","21–100%","DPOC acidótico, edema agudo cardiogênico, pós-extubação selecionado.","Cautela em SARA hipoxêmica de novo; contraindicações de via aérea/choque."],
 ["VM invasiva","Ventilador","21–100%","Falência respiratória, proteção de via aérea, choque/alteração neurológica.","Usar estratégia protetora, metas e prevenção de VILI/VAP."]
];
const VENT_MODES = [
 ["VCV / A-C Volume","Volume/fluxo","VT, FR, PEEP, FiO₂, fluxo, pausa, trigger","Garante VT/minuto; facilita Pplat/ΔP.","Fluxo insuficiente, Ppico alta por resistência, assincronia se drive alto."],
 ["PCV / A-C Pressão","Pressão inspiratória","Pinsp, Ti, FR, PEEP, FiO₂, rise time","Limita pressão, fluxo desacelerado, pode melhorar sincronia.","VT varia com complacência/resistência/esforço; monitorar VT e VM."],
 ["PRVC","VT alvo com pressão adaptativa","VT alvo, limites de pressão, FR, PEEP, FiO₂","Busca VT com menor pressão possível.","Pode reduzir suporte durante aumento de drive; monitorar esforço/assincronia."],
 ["PSV","Pressão de suporte","PS, PEEP, FiO₂, trigger, rise time, ciclagem, backup","Conforto e desmame.","VT variável; apneia; ciclagem precoce/tardia; sobreassistência."],
 ["BiPAP / VNI","IPAP/EPAP","IPAP, EPAP, FiO₂, backup, trigger, ciclagem","Falência hipercápnica; reduz trabalho respiratório.","Vazamento, aspiração, atraso de intubação em hipoxemia grave."],
 ["APRV / BiLevel","Tempo em pressão alta/baixa","P-high, T-high, P-low, T-low, FiO₂","Recrutamento e respiração espontânea em casos selecionados.","Requer expertise; monitorar VT espontâneo, CO₂, hemodinâmica."]
];
const PROTECTIVE_TARGETS = [
 ["VT em SARA/ARDS","4–8 ml/kg PBW; alvo comum 6 ml/kg","Ajustar VT e reavaliar pH/PaCO₂, Pplat e ΔP."],
 ["Pplat","<30 cmH₂O","Reduzir VT, checar complacência/auto-PEEP/assincronia/pneumotórax."],
 ["Driving pressure ΔP","Idealmente ≤14–15 cmH₂O","Reduzir VT; titular PEEP por melhor complacência e tolerância."],
 ["SpO₂ em SARA/VM","88–95% ou PaO₂ 55–80 mmHg","Ajustar FiO₂/PEEP; evitar hiperóxia."],
 ["FR","Suficiente para pH; evitar auto-PEEP; usualmente ≤35/min","Aumentar com cautela se acidose; verificar fluxo expiratório."],
 ["Cstat","Tendência importa; baixa sugere pulmão rígido/edema/atelectasia","Revisar PEEP, pronação, recrutamento, causa de base e pressão abdominal."],
 ["Potência mecânica","Quanto menor com gasometria aceitável; alerta se muito alta","Reduzir VT/ΔP/FR/PEEP/Ppico conforme mecanismo."]
];
const FORMULAS = [
 ["PBW masculino","50 + 0,91 × (altura_cm − 152,4)","VT protetor"],
 ["PBW feminino","45,5 + 0,91 × (altura_cm − 152,4)","VT protetor"],
 ["P/F","PaO₂ / FiO₂","Gravidade da hipoxemia/SARA"],
 ["S/F","SpO₂ / FiO₂","Estimativa sem gasometria; melhor com SpO₂ ≤97%"],
 ["ROX","(SpO₂ / FiO₂) / FR","Risco de falha de CBAF/HFNC"],
 ["ΔP","Pplat − PEEP total","Strain/carga mecânica"],
 ["Cstat","VT / (Pplat − PEEP)","Complacência estática"],
 ["Resistência","(Ppico − Pplat) / fluxo(L/s)","Obstrução/tubo/broncoespasmo"],
 ["VM","VT(L) × FR","Ventilação minuto"],
 ["PAO₂","FiO₂×(Patm−47) − PaCO₂/RQ","Gradiente A–a"],
 ["CaO₂","1,34×Hb×SaO₂ + 0,003×PaO₂","Conteúdo arterial de O₂"],
 ["Winter","PaCO₂ esperada = 1,5×HCO₃ + 8 ±2","Compensação da acidose metabólica"],
 ["Potência mecânica VCV simplificada","0,098×FR×VT(L)×(Ppico−0,5×ΔP)","Carga mecânica global"]
];
const LOW_PEEP = [[.30,"5"],[.40,"5–8"],[.50,"8–10"],[.60,"10"],[.70,"10–14"],[.80,"14"],[.90,"14–18"],[1,"18–24"]];
const HIGH_PEEP = [[.30,"5–14"],[.40,"14–16"],[.50,"16–18"],[.60,"18–20"],[.70,"18–20"],[.80,"20–22"],[.90,"22"],[1,"22–24"]];
const ASYNC_RULES = {
 fluxo_inspiratorio_insuficiente:{label:"Fluxo inspiratório insuficiente / flow starvation", cues:["concavidade_pressao","queda_pressao_inspiratoria","desconforto_inspiratorio"], actions:["Aumentar fluxo inspiratório em VCV ou reduzir rise time em PCV/PSV, conforme ventilador.","Considerar fluxo desacelerado, PCV/PSV ou ajuste de sedoanalgesia se drive muito alto.","Reavaliar VT, Pplat e ΔP após qualquer aumento de suporte."]},
 disparo_ineficaz:{label:"Esforço ineficaz / trigger não reconhecido", cues:["deflexao_sem_ciclo","auto_peep","fraqueza"], actions:["Aumentar sensibilidade do trigger com cuidado para evitar auto-trigger.","Tratar auto-PEEP: reduzir FR/VT, prolongar TE, broncodilatar, aspirar secreções e ajustar PEEP externa.","Reduzir sobreassistência se drive muito baixo; revisar sedação e modo ventilatório."]},
 duplo_disparo:{label:"Duplo disparo / breath stacking", cues:["duas_inspiracoes_seguidas","vt_baixo_para_drive","ti_curto"], actions:["Aumentar tempo inspiratório ou ajustar ciclagem se o ventilador encerra a inspiração cedo demais.","Revisar se VT está baixo demais para o drive; manter limites protetores de Pplat/ΔP.","Otimizar analgesia/sedação; em SARA grave com metas inviáveis, discutir bloqueio neuromuscular temporário."]},
 ciclagem_precoce:{label:"Ciclagem precoce", cues:["expiracao_precoce","duas_inspiracoes_seguidas","ti_curto"], actions:["Em PSV, reduzir percentual de ciclagem ou aumentar Ti máximo, conforme ventilador.","Em PCV, aumentar Ti se seguro; checar aprisionamento aéreo após ajuste."]},
 ciclagem_tardia:{label:"Ciclagem tardia", cues:["contracao_expiratoria","pico_pressao_final_inspiracao","ti_longo"], actions:["Encurtar Ti ou aumentar percentual de ciclagem em PSV.","Revisar vazamento, resistência expiratória e auto-PEEP."]},
 auto_trigger:{label:"Auto-trigger", cues:["ciclos_sem_esforco","vazamento","condensado_circuito"], actions:["Corrigir vazamentos e condensado no circuito; checar balonete e interface.","Reduzir sensibilidade do trigger se houver disparos sem esforço real."]},
 auto_peep:{label:"Auto-PEEP / hiperinsuflação dinâmica", cues:["fluxo_expiratorio_nao_zera","auto_peep","expiracao_prolongada"], actions:["Reduzir FR e/ou VT, aumentar fluxo inspiratório para encurtar Ti e prolongar TE.","Tratar broncoespasmo/secreções; checar obstrução de tubo e circuito.","Aplicar PEEP externa cuidadosamente em obstrução para reduzir esforço de disparo, sem piorar hiperinsuflação."]},
 reverse_trigger:{label:"Reverse triggering", cues:["esforco_apos_mandatoria","padrao_repetitivo","sedacao_profunda"], actions:["Revisar profundidade de sedação e drive respiratório.","Ajustar modo, FR, Ti e suporte; se breath stacking perigoso em SARA, discutir bloqueio temporário."]}
};
const CUE_LABELS = {
 concavidade_pressao:"VCV: curva pressão-tempo côncava/queda inspiratória", queda_pressao_inspiratoria:"Queda de pressão durante inspiração com desconforto", desconforto_inspiratorio:"Desconforto/uso muscular na inspiração", deflexao_sem_ciclo:"Deflexões de pressão/fluxo sem disparar ciclo", auto_peep:"Auto-PEEP suspeita/necessidade de esforço para disparar", fraqueza:"Esforço fraco, sedação profunda ou fraqueza", duas_inspiracoes_seguidas:"Dois ciclos seguidos / breath stacking", vt_baixo_para_drive:"VT parece baixo para drive/esforço do paciente", ti_curto:"Tempo inspiratório curto / término precoce da inspiração", expiracao_precoce:"Paciente ainda inspira quando ventilador cicla para expiração", contracao_expiratoria:"Contração expiratória ativa no fim da inspiração", pico_pressao_final_inspiracao:"Pico/espícula de pressão no fim da inspiração", ti_longo:"Tempo inspiratório longo / paciente tenta expirar", ciclos_sem_esforco:"Ciclos sem esforço aparente", vazamento:"Vazamento em cuff/interface/circuito", condensado_circuito:"Condensado/água no circuito", fluxo_expiratorio_nao_zera:"Fluxo expiratório não volta a zero antes do próximo ciclo", expiracao_prolongada:"Doença obstrutiva/expiração prolongada", esforco_apos_mandatoria:"Esforço neural após ciclo mandatório", padrao_repetitivo:"Padrão repetitivo acoplado à ventilação mandatória", sedacao_profunda:"Sedação profunda com esforço reflexo suspeito"
};
const ids = ["age","sex","height_cm","weight_kg","support","vent_mode","hypercapnia_risk","ards_suspected","acute_onset","bilateral_opacities","noncardiogenic_edema","spo2","rr","hr","sbp","high_wob","shock","altered_mental_status","airway_unprotected","niv_contraindication","ph","paco2","pao2","hco3","be","lactate","sao2","fio2","vt_ml","peep","pplat","ppeak","pinsp","pexp","ti","te","flow_l_min","map_cmH2O","na","cl","albumin","hb","patm","rq"];
let state = {}, analysis = {}, recommendations = [];
function el(id){return document.getElementById(id)}
function safeDiv(n,d){n=Number(n);d=Number(d);return isFinite(n)&&isFinite(d)&&Math.abs(d)>1e-12?n/d:null}
function fmt(v,d=1,s=""){return v===null||v===undefined||!isFinite(v)?"—":Number(v).toFixed(d)+s}
function clamp(v,l,h){return Math.max(l,Math.min(h,v))}
function readData(){const d={}; ids.forEach(id=>{const node=el(id); if(!node) return; if(node.type==="checkbox") d[id]=node.checked; else if(node.tagName==="SELECT") d[id]=node.value; else {const n=parseFloat(node.value); d[id]=isNaN(n)?null:n;}}); return d;}
function predictedBodyWeight(sex,height){const h=Math.max(Number(height)||152.4,152.4); return String(sex).toLowerCase().startsWith("f") ? 45.5+0.91*(h-152.4) : 50+0.91*(h-152.4)}
function tidalTargets(pbw){return {"4 ml/kg":4*pbw,"5 ml/kg":5*pbw,"6 ml/kg":6*pbw,"7 ml/kg":7*pbw,"8 ml/kg":8*pbw}}
function alveolarO2(fio2,paco2,patm=760,rq=.8){return fio2*(patm-47)-(paco2/rq)}
function expectedCompensation(d){const result={status:"indeterminado",primary:"indeterminado",expected:null,mixed_flag:null}; const {ph,paco2,hco3}=d; if(ph==null||paco2==null||hco3==null) return result; if(ph<7.35){result.status="acidemia"; const metab=hco3<22, resp=paco2>45; if(metab&&resp){result.primary="distúrbio misto provável: acidose metabólica + acidose respiratória"; const exp=1.5*hco3+8; result.expected=[exp-2,exp+2]; result.mixed_flag="PaCO₂ acima do esperado para acidose metabólica sugere componente respiratório."} else if(metab){result.primary="acidose metabólica"; const exp=1.5*hco3+8; result.expected=[exp-2,exp+2]; result.mixed_flag=paco2>exp+2?"compensação insuficiente: acidose respiratória associada":paco2<exp-2?"PaCO₂ abaixo do esperado: alcalose respiratória associada":"compensação respiratória compatível"} else if(resp){result.primary="acidose respiratória"; const delta=paco2-40; result.expected=[24+1*(delta/10),24+3.5*(delta/10)]; result.mixed_flag="comparar HCO₃⁻ com faixa aguda/crônica; HCO₃⁻ muito baixo sugere acidose metabólica associada."} else result.primary="acidemia sem padrão simples"} else if(ph>7.45){result.status="alcalemia"; const metab=hco3>26, resp=paco2<35; if(metab&&resp){result.primary="distúrbio misto provável: alcalose metabólica + alcalose respiratória"} else if(metab){result.primary="alcalose metabólica"; const delta=hco3-24, low=40+.60*delta, high=Math.min(40+.75*delta,55); result.expected=[low,high]; result.mixed_flag=paco2<low?"PaCO₂ abaixo do esperado: alcalose respiratória associada":paco2>high?"PaCO₂ acima do esperado: acidose respiratória associada":"compensação respiratória compatível"} else if(resp){result.primary="alcalose respiratória"; const delta=40-paco2; result.expected=[24-4.5*(delta/10),24-2*(delta/10)]; result.mixed_flag="comparar HCO₃⁻ com faixa aguda/crônica; HCO₃⁻ alto sugere alcalose metabólica associada."} else result.primary="alcalemia sem padrão simples"} else {result.status="pH próximo do normal"; if(paco2>45&&hco3>26) result.primary="acidose respiratória compensada ou distúrbio misto normalizando pH"; else if(paco2<35&&hco3<22) result.primary="alcalose respiratória compensada ou distúrbio misto normalizando pH"; else if(hco3<22) result.primary="acidose metabólica compensada"; else if(hco3>26) result.primary="alcalose metabólica compensada"; else result.primary="sem distúrbio ácido-base simples evidente";} return result;}
function berlin(pf,peep){if(pf==null)return"indeterminado"; if(peep==null||peep<5)return"não classifica Berlin sem PEEP/CPAP ≥ 5"; if(pf<=100)return"SARA/ARDS grave"; if(pf<=200)return"SARA/ARDS moderada"; if(pf<=300)return"SARA/ARDS leve"; return"sem hipoxemia compatível por P/F";}
function mechanics(d,pbw){const vtL=d.vt_ml!=null?d.vt_ml/1000:null; const mv=vtL!=null&&d.rr!=null?vtL*d.rr:null; const vtkg=pbw&&d.vt_ml!=null?d.vt_ml/pbw:null; let dp=null,cstat=null,cdyn=null,res=null,mp=null; if(d.pplat!=null&&d.peep!=null){dp=d.pplat-d.peep; if(dp>0&&d.vt_ml!=null)cstat=d.vt_ml/dp;} if(d.ppeak!=null&&d.peep!=null&&d.vt_ml!=null){const dd=d.ppeak-d.peep; if(dd>0) cdyn=d.vt_ml/dd;} if(d.ppeak!=null&&d.pplat!=null&&d.flow_l_min){const fls=d.flow_l_min/60; if(fls>0) res=(d.ppeak-d.pplat)/fls;} if(vtL!=null&&d.rr!=null&&d.ppeak!=null&&dp!=null) mp=.098*d.rr*vtL*(d.ppeak-.5*dp); return {vt_l:vtL,minute_ventilation_l_min:mv,vt_per_kg_pbw:vtkg,driving_pressure:dp,static_compliance_ml_cmH2O:cstat,dynamic_compliance_ml_cmH2O:cdyn,airway_resistance_cmH2O_L_s:res,mechanical_power_j_min_simplified:mp};}
function oxygenTarget(d){if(d.hypercapnia_risk)return[88,92,"risco de hipercapnia/DPOC: alvo controlado"]; if(["VM invasiva","TQT/VM"].includes(d.support)&&d.ards_suspected)return[88,95,"SARA/ARDS em VM: alvo tipo ARDSNet"]; return[94,98,"paciente agudo sem risco de hipercapnia: alvo usual"];}
function analyze(d){const pbw=predictedBodyWeight(d.sex,d.height_cm); const pf=safeDiv(d.pao2,d.fio2); const sf=safeDiv(d.spo2,d.fio2); const rox=safeDiv(sf,d.rr); const aa=(d.fio2&&d.paco2&&d.pao2)?alveolarO2(d.fio2,d.paco2,d.patm||760,d.rq||.8)-d.pao2:null; const ca=(d.hb&&d.sao2&&d.pao2)?1.34*d.hb*(d.sao2/100)+.003*d.pao2:null; const ag=(d.na&&d.cl&&d.hco3)?d.na-(d.cl+d.hco3):null; const agc=ag==null?null:(d.albumin?ag+2.5*(4-d.albumin):ag); const delta=(agc!=null&&d.hco3!=null&&Math.abs(24-d.hco3)>1e-9)?(agc-12)/(24-d.hco3):null; const hco3corr=(agc!=null&&d.hco3!=null)?d.hco3+(agc-12):null; const mech=mechanics(d,pbw); const oi=(d.map_cmH2O&&d.pao2)?safeDiv(d.fio2*d.map_cmH2O*100,d.pao2):null; return {pbw_kg:pbw,tidal_volume_targets_ml:tidalTargets(pbw),pf_ratio:pf,sf_ratio:sf,rox_index:rox,aa_gradient:aa,ca_o2_ml_dl:ca,anion_gap:ag,anion_gap_corrected:agc,delta_ratio:delta,corrected_bicarbonate:hco3corr,acid_base:expectedCompensation(d),mechanics:mech,ards_severity:berlin(pf,d.peep),oxygen_target:oxygenTarget(d),oxygenation_index:oi};}
function addRec(recs,severity,title,rationale,actions,safety="Confirmar com avaliação clínica, tendência temporal e protocolo institucional."){recs.push({severity,title,rationale,actions,safety,score:{"Emergência":0,"Alto":1,"Moderado":2,"Desmame":3,"Baixo":4,"OK":5}[severity]??9});}
function generateRecommendations(d,a){const recs=[]; const pf=a.pf_ratio, rox=a.rox_index, sf=a.sf_ratio, m=a.mechanics; const [tl,th,tlabel]=a.oxygen_target; const dp=m.driving_pressure, cstat=m.static_compliance_ml_cmH2O, vtkg=m.vt_per_kg_pbw, mp=m.mechanical_power_j_min_simplified; const flags=[]; if(d.airway_unprotected)flags.push("via aérea não protegida"); if(d.altered_mental_status)flags.push("rebaixamento/agitação impeditiva"); if(d.shock||d.sbp<90)flags.push("choque/hipotensão"); if(d.spo2<85&&d.fio2>=.60)flags.push("hipoxemia crítica apesar de FiO₂ alta"); if(d.ph<7.20&&d.paco2>60)flags.push("acidose respiratória grave"); if(d.rr>=40||(d.rr>=35&&d.high_wob))flags.push("exaustão ventilatória provável"); if(flags.length)addRec(recs,"Emergência","Preparar escalonamento imediato e suporte avançado de via aérea","Critérios de gravidade detectados: "+flags.join(", ") + ".",["Acionar equipe experiente em via aérea/UTI e checar equipamentos de intubação difícil.","Otimizar pré-oxigenação com dispositivo de maior FiO₂ efetiva, evitando atraso se houver falência clínica.","Corrigir causas reversíveis simultaneamente: broncoespasmo, pneumotórax, edema pulmonar, secreção, sepse/choque, deslocamento de tubo."],"Não retardar intubação por tentativa prolongada de CBAF/VNI quando houver choque, via aérea insegura ou deterioração rápida.");
 if(d.spo2<tl||d.pao2<55){ if(["Ar ambiente","CN O2","Máscara simples","Venturi","MR"].includes(d.support)) addRec(recs,d.spo2<90?"Alto":"Moderado","Hipoxemia abaixo do alvo: escalar oxigenoterapia de forma controlada",`SpO₂ ${fmt(d.spo2,0,'%')} abaixo do alvo (${tl}-${th}%; ${tlabel}).`,["Conferir sensor, perfusão e gasometria; tratar causa de base.","Se em CN O₂ ou máscara simples: considerar Venturi se precisar FiO₂ controlada, ou máscara com reservatório se hipoxemia importante sem hipercapnia.","Se necessidade de FiO₂ alta, taquipneia ou trabalho respiratório: considerar CBAF/HFNC; em DPOC acidótico ou edema pulmonar cardiogênico, considerar VNI se não houver contraindicação.","Reavaliar resposta clínica e gasométrica; se piora, acionar equipe para via aérea avançada."]); else if(d.support==="CBAF/HFNC") addRec(recs,"Alto","CBAF/HFNC com resposta insuficiente: risco de falha",`SpO₂/FiO₂=${fmt(sf,0)} e ROX=${fmt(rox,2)}; hipoxemia persiste apesar de suporte não invasivo de alto fluxo.`,["Aumentar fluxo para reduzir entrainment e trabalho respiratório, se tolerado e disponível.","Ajustar FiO₂ para atingir alvo, evitando hiperóxia sustentada.","Se ROX baixo ou em queda, trabalho respiratório alto, instabilidade ou alteração neurológica: preparar intubação/VM invasiva."]); else if(d.support==="VNI/CPAP/BiPAP") addRec(recs,"Alto","VNI com hipoxemia persistente: evitar atraso de intubação",`SpO₂ ${fmt(d.spo2,0,'%')} abaixo do alvo em VNI; contraindicações=${d.niv_contraindication}.`,["Checar interface, vazamento, sincronia, EPAP/PEEP, FiO₂ e esforço do paciente.","Se DPOC/hipercapnia: titular IPAP para ventilação e EPAP para oxigenação, monitorando volume corrente e vazamentos.","Se insuficiência respiratória hipoxêmica de novo/SARA com FiO₂ alta, P/F baixo ou esforço intenso: planejar VM invasiva em vez de VNI prolongada."]); else if(["VM invasiva","TQT/VM"].includes(d.support)) addRec(recs,"Alto","Hipoxemia em VM: otimizar FiO₂/PEEP e pesquisar causa reversível",`P/F=${fmt(pf,0)}; alvo ${tl}-${th}% em SARA/ARDS invasiva quando aplicável.`,["Ajustar FiO₂ inicialmente para segurança; depois titular PEEP/FiO₂ por tabela ou pela melhor complacência/hemodinâmica.","Checar tubo, secreções, atelectasia, pneumotórax, edema, assincronia, auto-PEEP e posição do paciente.","Se SARA moderada-grave: considerar pronação prolongada e estratégia protetora rigorosa."]);}
 if(d.spo2>th+1&&d.fio2>.40)addRec(recs,"Baixo","Possível excesso de oxigênio: reduzir FiO₂ gradualmente",`SpO₂ ${fmt(d.spo2,0,'%')} está acima do alvo (${tl}-${th}%).`,["Reduzir FiO₂ em pequenos passos mantendo SpO₂ no alvo.","Em VM, preferir reduzir FiO₂ antes de reduzir PEEP quando há dependência de recrutamento, salvo hiperinsuflação/hemodinâmica desfavorável."]);
 if(d.support==="CBAF/HFNC"&&rox!=null){ if(rox<3.85)addRec(recs,"Alto","ROX muito baixo: forte alerta de falha de CBAF/HFNC",`ROX=${fmt(rox,2)}. Valores baixos, especialmente persistentes ou em queda, aumentam preocupação com falha.`,["Reavaliar imediatamente esforço ventilatório, nível de consciência e hemodinâmica.","Aumentar fluxo/FiO₂ se apropriado, mas preparar intubação se não houver resposta clínica rápida.","Evitar que o conforto aparente mas com hipoxemia profunda atrase escalonamento."]); else if(rox<4.88)addRec(recs,"Moderado","ROX intermediário: zona cinzenta para CBAF/HFNC",`ROX=${fmt(rox,2)}. Interpretar tendência e contexto clínico.`,["Manter monitorização estreita de ROX, SpO₂/FiO₂, FR, esforço e gasometria.","Se ROX cair, FiO₂ subir ou trabalho respiratório persistir: escalar suporte."]); else addRec(recs,"OK","ROX favorável para continuidade de CBAF/HFNC, se clínica compatível",`ROX=${fmt(rox,2)} e SpO₂ no alvo sugerem resposta aceitável no momento.`,["Manter metas de SpO₂, reduzir FiO₂/fluxo quando estável e tratar a causa de base."]);}
 if(d.support==="VNI/CPAP/BiPAP"){ if(d.niv_contraindication||d.airway_unprotected||d.shock)addRec(recs,"Emergência","Contraindicação ou alto risco para VNI","Há fatores que tornam VNI insegura ou pouco provável de sucesso.",["Não manter VNI como estratégia principal se via aérea é insegura, há choque, vômitos/aspiração, rebaixamento importante ou intolerância grave.","Preparar suporte invasivo com equipe experiente e plano de resgate."]); else if(d.hypercapnia_risk&&d.ph<7.35&&d.paco2>45)addRec(recs,"Moderado","Perfil compatível com benefício de VNI em falência ventilatória hipercápnica",`pH=${fmt(d.ph,2)}, PaCO₂=${fmt(d.paco2,0)} mmHg; sem contraindicação informada.`,["Titular IPAP para reduzir PaCO₂ e trabalho respiratório; EPAP para vencer auto-PEEP/oxigenação.","Ajustar trigger, rise time, ciclagem e interface para minimizar assincronia e vazamento.","Se pH piorar, FR/esforço persistir ou consciência/hemodinâmica deteriorar: escalar para VM invasiva."]); else if(pf!=null&&pf<=150&&d.fio2>=.60)addRec(recs,"Alto","VNI em hipoxemia grave/SARA: risco de falha e atraso",`P/F=${fmt(pf,0)} com FiO₂=${fmt(d.fio2,2)}.`,["Usar VNI apenas com monitorização intensiva e critério claro de falha.","Considerar intubação precoce se esforço intenso, assincronia, instabilidade ou necessidade de FiO₂/pressões crescentes."]);}
 if(["VM invasiva","TQT/VM"].includes(d.support)){ if(vtkg!=null){ if(vtkg>8)addRec(recs,"Alto","Volume corrente acima da faixa protetora",`VT/PBW=${fmt(vtkg,1)} ml/kg. Em SARA/ARDS, usar 4–8 ml/kg PBW, usualmente alvo inicial 6 ml/kg.`,["Reduzir VT em passos, monitorando pH/PaCO₂, Pplat e sincronia.","Aceitar hipercapnia permissiva quando clinicamente apropriado, evitando acidemia grave."]); else if(vtkg<4)addRec(recs,"Moderado","VT muito baixo: checar ventilação minuto, drive e espaço morto",`VT/PBW=${fmt(vtkg,1)} ml/kg.`,["Avaliar pH/PaCO₂, sincronia e necessidade de ajuste de FR, pressão ou modo, sem ultrapassar limites protetores."]);}
  if(d.pplat&&d.pplat>30)addRec(recs,"Alto","Pressão de platô acima do limite protetor",`Pplat=${fmt(d.pplat,0)} cmH₂O.`,["Reduzir VT em 0,5–1 ml/kg PBW até mínimo usual de 4 ml/kg, se necessário.","Checar complacência, auto-PEEP, assincronia, pneumotórax, edema e pressão abdominal.","Se Pplat persistir alta com VT mínimo, solicitar avaliação avançada de ventilação/ECMO conforme recursos."]);
  if(dp!=null){ if(dp>15)addRec(recs,"Alto","Driving pressure elevada",`ΔP=${fmt(dp,1)} cmH₂O; Cstat=${fmt(cstat,0)} ml/cmH₂O.`,["Reduzir VT se possível e buscar PEEP que melhore complacência sem hiperinsuflação/hemodinâmica ruim.","Em SARA moderada-grave, associar pronação e tratar causas reversíveis de baixa complacência."]); else if(dp<=14&&d.pplat<=30)addRec(recs,"OK","Mecânica dentro de metas protetoras principais",`Pplat=${fmt(d.pplat,0)} cmH₂O e ΔP=${fmt(dp,1)} cmH₂O.`,["Manter vigilância de tendência, sincronia, gasometria e necessidade de sedação."]);}
  if(mp!=null&&mp>17)addRec(recs,"Moderado","Potência mecânica elevada: reduzir carga ventilatória total se possível",`Potência mecânica simplificada≈${fmt(mp,1)} J/min.`,["Revisar componentes: VT, ΔP, FR, PEEP e Ppico.","Evitar aumento isolado de FR para acidose se houver auto-PEEP/hiperinsuflação dinâmica."]);
  if(d.ph<7.25&&d.paco2>50)addRec(recs,"Moderado","Acidose respiratória/hipercapnia em VM: otimizar ventilação minuto sem perder proteção pulmonar",`pH=${fmt(d.ph,2)}, PaCO₂=${fmt(d.paco2,0)} mmHg.`,["Aumentar FR até limite seguro, checando se fluxo expiratório zera antes do próximo ciclo.","Reduzir espaço morto instrumental e tratar broncoespasmo/secreção.","Aumentar VT apenas se Pplat/ΔP permanecerem seguros; considerar tampão/correção específica conforme contexto clínico."]);
  if(d.ards_suspected&&d.acute_onset&&d.bilateral_opacities&&d.noncardiogenic_edema){ if(pf!=null&&pf<=150&&d.peep>=5)addRec(recs,"Alto","SARA moderada-grave: considerar pronação prolongada",`P/F=${fmt(pf,0)} com PEEP=${fmt(d.peep,0)} cmH₂O; critérios clínicos de SARA marcados.`,["Pronar por sessões prolongadas se não houver contraindicação e equipe treinada.","Garantir VM protetora, sedoanalgesia adequada, proteção ocular/pele e prevenção de eventos de tubo/cateteres."]); if(pf!=null&&pf<150&&(d.high_wob||d.pplat>30||(dp!=null&&dp>15)))addRec(recs,"Moderado","Considerar bloqueio neuromuscular se metas ventilatórias não são alcançadas com sedação adequada","Hipoxemia moderada-grave associada a esforço/assincronia ou metas protetoras difíceis.",["Antes do bloqueio: analgesia/sedação adequadas, metas e monitorização definidas.","Usar pelo menor tempo necessário e reavaliar diariamente, conforme protocolo e risco de fraqueza adquirida na UTI."]); if(pf!=null&&pf<80&&d.fio2>=.80&&d.peep>=10)addRec(recs,"Alto","Hipoxemia refratária: discutir resgate avançado/centro ECMO",`P/F=${fmt(pf,0)} com FiO₂=${fmt(d.fio2,2)} e PEEP=${fmt(d.peep,0)}.`,["Confirmar otimização: pronação, PEEP, recrutabilidade, hemodinâmica, tubo, pneumotórax, posição e causa de base.","Acionar centro experiente para avaliação de ECMO VV se critérios institucionais forem preenchidos."]);}
  if(d.fio2<=.40&&d.peep<=8&&d.spo2>=tl&&!d.shock&&!d.altered_mental_status&&d.ph>=7.30&&d.rr<=30)addRec(recs,"Desmame","Critérios favoráveis para reduzir suporte / teste de respiração espontânea","FiO₂ e PEEP baixos, estabilidade hemodinâmica e gasometria aceitável no momento.",["Avaliar despertar, força de tosse, secreção, proteção de via aérea e causa de intubação resolvida.","Considerar TRE/SBT conforme protocolo local; interromper se taquicardia, dessaturação, sudorese, uso de musculatura acessória ou desconforto importante."]);
 }
 const acid=a.acid_base; if(acid.primary&&acid.primary!=="sem distúrbio ácido-base simples evidente"){let sev=(d.ph<7.20||d.ph>7.60||d.lactate>=4)?"Alto":"Moderado"; addRec(recs,sev,"Gasometria: "+acid.primary,`Estado: ${acid.status}; ${acid.mixed_flag||"interpretar com eletrólitos, albumina, lactato e clínica."}`,["Tratar causa primária; não corrigir número isolado sem entender mecanismo.","Usar anion gap/delta gap se Na⁺/Cl⁻/albumina estiverem disponíveis.","Em hipercapnia, revisar ventilação alveolar; em lactato elevado, revisar perfusão, sepse, hipoxemia, convulsão/drogas e clearance hepático."]);}
 if(d.lactate>=4)addRec(recs,"Alto","Lactato elevado: sinal de alto risco sistêmico",`Lactato=${fmt(d.lactate,1)} mmol/L.`,["Pesquisar choque/hipoperfusão, sepse, hipoxemia, anemia grave, convulsões, drogas beta-adrenérgicas e insuficiência hepática.","Integrar com pressão, diurese, perfusão periférica, necessidade de vasopressor e tendência do lactato."]);
 if(!recs.length)addRec(recs,"OK","Sem alerta crítico detectado pelos dados inseridos","Os parâmetros principais não cruzaram limites de risco do protótipo.",["Manter vigilância, revisar tendências e individualizar a conduta."]); return recs.sort((a,b)=>a.score-b.score);}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??"—"}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function metric(label,value,note=""){return `<article class="metric"><small>${label}</small><strong>${value}</strong><em>${note}</em></article>`}
function render(){state=readData(); analysis=analyze(state); recommendations=generateRecommendations(state,analysis); renderMetrics(); renderBanner(); renderRecommendations(); renderGas(); renderProtective(); renderSim(); renderAsync(); renderQuick(); renderSnapshots();}
function renderMetrics(){const m=analysis.mechanics; const [tl,th,label]=analysis.oxygen_target; el("metricGrid").innerHTML=[metric("P/F",fmt(analysis.pf_ratio,0),analysis.ards_severity),metric("ROX",fmt(analysis.rox_index,2),"CBAF/HFNC"),metric("VT/PBW",fmt(m.vt_per_kg_pbw,1," ml/kg"),"protetor 4–8"),metric("ΔP",fmt(m.driving_pressure,1," cmH₂O"),"alvo ≤14–15"),metric("Cstat",fmt(m.static_compliance_ml_cmH2O,0," ml/cmH₂O"),"tendência importa"),metric("Alvo SpO₂",`${tl}–${th}%`,label)].join("");}
function renderBanner(){const b=el("criticalBanner"); const top=recommendations[0]; b.className="banner show "; if(top.severity==="Emergência"){b.className+="emergencia";b.textContent="🚨 Existem alertas de emergência. Revise a primeira recomendação antes de navegar pelas demais abas."} else if(recommendations.some(r=>r.severity==="Alto")){b.className+="alto";b.textContent="🔥 Existem alertas de alto risco. Priorize oxigenação, ventilação protetora e critérios de falha de suporte."} else {b.className+="ok";b.textContent="✅ Nenhum alerta crítico pelo motor do protótipo com os dados inseridos."}}
function renderRecommendations(){const icons={"Emergência":"🚨","Alto":"🔥","Moderado":"⚠️","Desmame":"🌱","Baixo":"ℹ️","OK":"✅"}; el("recommendations").innerHTML=recommendations.map(r=>`<article class="rec-card sev-${r.severity}"><h3>${icons[r.severity]||"•"} ${r.severity} — ${r.title}</h3><p><strong>Por quê:</strong> ${r.rationale}</p><ul>${r.actions.map(a=>`<li>${a}</li>`).join("")}</ul><div class="safety"><strong>Trava de segurança:</strong> ${r.safety}</div></article>`).join("");}
function renderGas(){const a=analysis, d=state, acid=a.acid_base; const cards=[metric("Estado do pH",acid.status,""),metric("Distúrbio principal",acid.primary,""),metric("Compensação esperada",acid.expected?`${fmt(acid.expected[0],1)}–${fmt(acid.expected[1],1)}`:"—","PaCO₂/HCO₃ esperado"),metric("Lactato",fmt(d.lactate,1," mmol/L"),d.lactate>=4?"alto risco":"")].join(""); const ox=table(["Parâmetro","Valor","Uso"],[["P/F",fmt(a.pf_ratio,0),"Gravidade hipoxemia/SARA"],["S/F",fmt(a.sf_ratio,0),"Estimativa quando sem gaso"],["ROX",fmt(a.rox_index,2),"Falha CBAF/HFNC"],["Gradiente A–a",fmt(a.aa_gradient,0," mmHg"),"V/Q, shunt, difusão"],["CaO₂",fmt(a.ca_o2_ml_dl,1," mL/dL"),"Conteúdo arterial de O₂"]]); const ag=table(["Parâmetro","Valor","Interpretação rápida"],[["AG",fmt(a.anion_gap,1),"Na − (Cl + HCO₃)"],["AG corrigido",fmt(a.anion_gap_corrected,1),"Corrige hipoalbuminemia"],["Δ/Δ",fmt(a.delta_ratio,2),"Distúrbio metabólico misto"],["HCO₃ corrigido",fmt(a.corrected_bicarbonate,1),">28 sugere alcalose metabólica associada; <22 NAGMA associada"]]); el("gasPanel").innerHTML=`<div class="quick-grid mini">${cards}</div><div class="info-card"><strong>🧠 Leitura do motor:</strong> ${acid.mixed_flag||"Use quadro clínico, eletrólitos e tendência temporal para confirmar distúrbios mistos."}</div><h3>Oxigenação</h3>${ox}<h3>Ânion gap / delta</h3>${ag}<h3>Fórmulas usadas</h3>${table(["Fórmula","Equação","Uso"],FORMULAS)}`;}
function renderProtective(){const a=analysis, d=state, m=a.mechanics, targets=a.tidal_volume_targets_ml; const targetRows=Object.entries(targets).map(([k,v])=>[k,fmt(v,0," mL")]); const mechRows=[["PBW",fmt(a.pbw_kg,1," kg")],["VT alvo 6 ml/kg",fmt(targets["6 ml/kg"],0," mL")],["VT atual/PBW",fmt(m.vt_per_kg_pbw,1," ml/kg")],["Pplat",fmt(d.pplat,0," cmH₂O")],["ΔP",fmt(m.driving_pressure,1," cmH₂O")],["Ventilação minuto",fmt(m.minute_ventilation_l_min,2," L/min")],["Cstat",fmt(m.static_compliance_ml_cmH2O,0," ml/cmH₂O")],["Resistência",fmt(m.airway_resistance_cmH2O_L_s,1," cmH₂O/L/s")],["Potência mecânica simplificada",fmt(m.mechanical_power_j_min_simplified,1," J/min")],["Índice de oxigenação",fmt(a.oxygenation_index,1)],["Classificação Berlin",a.ards_severity]]; el("protectivePanel").innerHTML=`<div class="quick-grid mini">${metric("PBW",fmt(a.pbw_kg,1," kg"),"base para VT")}${metric("VT 6 ml/kg",fmt(targets["6 ml/kg"],0," mL"),"alvo inicial")}${metric("Pplat",fmt(d.pplat,0," cmH₂O"),"meta <30")}${metric("ΔP",fmt(m.driving_pressure,1," cmH₂O"),"meta ≤14–15")}</div><h3>Alvos de VT por PBW</h3>${table(["Alvo","Volume corrente"],targetRows)}<h3>Mecânica respiratória</h3>${table(["Parâmetro","Valor"],mechRows)}<h3>PEEP/FiO₂ — tabela baixa</h3>${table(["FiO₂","PEEP sugerida cmH₂O"],LOW_PEEP)}<h3>PEEP/FiO₂ — tabela alta</h3>${table(["FiO₂","PEEP sugerida cmH₂O"],HIGH_PEEP)}<h3>Checklist protetor</h3>${table(["Parâmetro","Meta prática","Ação se fora"],PROTECTIVE_TARGETS)}`;}
function simulate(){const mode=el("sim_mode").value, rr=+el("sim_rr").value||20, vt_ml=+el("sim_vt").value||420, peep=+el("sim_peep").value||8, c=+el("sim_c").value||35, r=+el("sim_r").value||12, ti_in=+el("sim_ti").value||.9, pinsp=+el("sim_pinsp").value||15; const dt=.02, breaths=3, cycle=60/Math.max(rr,1), ti=clamp(ti_in,.2,Math.max(.21,cycle-.1)), te=Math.max(cycle-ti,dt), vtL=Math.max(vt_ml,1)/1000, cLCM=Math.max(c,1)/1000, res=Math.max(r,.1), tau=res*cLCM; let rows=[], volumeStart=0, residual=0, tg=0; for(let b=0;b<breaths;b++){ if(mode.startsWith("VC")||mode==="PRVC"){const flow=vtL/ti; for(let t=0;t<ti;t+=dt){const volume=volumeStart+flow*t, pressure=peep+volume/cLCM+res*flow; rows.push({t:tg+t,p:pressure,f:flow*60,v:volume*1000});} var vEnd=volumeStart+vtL;} else {const dp=Math.max(pinsp,1), vInf=cLCM*dp; for(let t=0;t<ti;t+=dt){const volume=vInf-(vInf-volumeStart)*Math.exp(-t/Math.max(tau,1e-6)), flow=((vInf-volumeStart)/Math.max(tau,1e-6))*Math.exp(-t/Math.max(tau,1e-6)); rows.push({t:tg+t,p:peep+dp,f:flow*60,v:volume*1000});} var vEnd=vInf-(vInf-volumeStart)*Math.exp(-ti/Math.max(tau,1e-6));} for(let t=0;t<te;t+=dt){const volume=vEnd*Math.exp(-t/Math.max(tau,1e-6)), flow=-(volume/Math.max(tau,1e-6)); rows.push({t:tg+ti+t,p:peep+volume/cLCM,f:flow*60,v:volume*1000});} volumeStart=vEnd*Math.exp(-te/Math.max(tau,1e-6)); residual=volumeStart*1000; tg+=cycle;} return {rows,cycle,te,tau,residual,auto_peep_risk:residual>.10*vtL*1000};}
function drawChart(canvasId, rows, key, label){const canvas=el(canvasId), ctx=canvas.getContext("2d"), w=canvas.width=canvas.clientWidth*devicePixelRatio, h=canvas.height=canvas.clientHeight*devicePixelRatio; ctx.clearRect(0,0,w,h); ctx.scale(devicePixelRatio,devicePixelRatio); const W=canvas.clientWidth,H=canvas.clientHeight,pad=36; ctx.strokeStyle="rgba(148,163,184,.25)"; ctx.lineWidth=1; for(let i=0;i<5;i++){const y=pad+(H-2*pad)*i/4; ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W/devicePixelRatio-pad,y);ctx.stroke();} const xs=rows.map(r=>r.t), ys=rows.map(r=>r[key]); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys); const sx=x=>pad+(x-minX)/(maxX-minX||1)*(W/devicePixelRatio-2*pad); const sy=y=>H-pad-(y-minY)/(maxY-minY||1)*(H-2*pad); ctx.strokeStyle="#38bdf8"; ctx.lineWidth=2; ctx.beginPath(); rows.forEach((r,i)=>{const x=sx(r.t), y=sy(r[key]); i?ctx.lineTo(x,y):ctx.moveTo(x,y)}); ctx.stroke(); ctx.fillStyle="#eaf2ff"; ctx.font="700 14px system-ui"; ctx.fillText(label,14,22); ctx.fillStyle="#9fb1ce"; ctx.font="12px system-ui"; ctx.fillText(`min ${fmt(minY,1)} • max ${fmt(maxY,1)}`,14,H-12);}
function renderSim(){const sim=simulate(); el("simMetrics").innerHTML=[metric("Ciclo",fmt(sim.cycle,2," s"),"60/FR"),metric("Te",fmt(sim.te,2," s"),"expiração"),metric("Constante τ",fmt(sim.tau,2," s"),"R×C"),metric("Volume residual",fmt(sim.residual,0," mL"),sim.auto_peep_risk?"⚠️ risco auto-PEEP":"")].join(""); drawChart("pressureChart",sim.rows,"p","Curva pressão × tempo (cmH₂O)"); drawChart("flowChart",sim.rows,"f","Curva fluxo × tempo (L/min)"); drawChart("volumeChart",sim.rows,"v","Curva volume × tempo (mL)");}
function analyzeAsync(){const checked=[...document.querySelectorAll(".async-cue:checked")].map(x=>x.value); return Object.entries(ASYNC_RULES).map(([key,rule])=>{const matches=rule.cues.filter(c=>checked.includes(c)); return matches.length?{key,label:rule.label,score:matches.length/rule.cues.length,matches,actions:rule.actions}:null}).filter(Boolean).sort((a,b)=>b.score-a.score);}
function renderAsync(){if(!el("asyncChecklist").dataset.ready){el("asyncChecklist").innerHTML=Object.entries(CUE_LABELS).map(([k,v])=>`<label class="check-option"><input class="async-cue" type="checkbox" value="${k}"> ${v}</label>`).join(""); el("asyncChecklist").dataset.ready="1"; document.querySelectorAll(".async-cue").forEach(c=>c.addEventListener("change",renderAsync)); el("asyncLibrary").innerHTML=table(["Assincronia","Achados-chave","Ações principais"],Object.values(ASYNC_RULES).map(r=>[r.label,r.cues.map(c=>CUE_LABELS[c]||c).join(" | "),r.actions.slice(0,2).join(" | ")]));}
 const results=analyzeAsync(); el("asyncResults").innerHTML=results.length?results.map(r=>`<article class="rec-card"><h3>🎯 ${r.label} — compatibilidade ${(r.score*100).toFixed(0)}%</h3><p><strong>Achados:</strong> ${r.matches.map(c=>CUE_LABELS[c]||c).join("; ")}</p><ul>${r.actions.map(a=>`<li>${a}</li>`).join("")}</ul></article>`).join(""):`<div class="info-card">ℹ️ Selecione achados para gerar hipóteses de assincronia e ações corretivas.</div>`;}
function renderQuick(){el("quickTables").innerHTML=`<h3>Dispositivos de oxigênio</h3>${table(["Dispositivo","Fluxo típico","FiO₂ aproximada","Uso prático","Alertas"],OXYGEN_DEVICES)}<h3>Modos ventilatórios</h3>${table(["Modo","Variável controlada","Ajustes centrais","Pontos fortes","Riscos/atenção"],VENT_MODES)}<h3>Fórmulas</h3>${table(["Fórmula","Equação","Uso"],FORMULAS)}<h3>PEEP/FiO₂ baixa</h3>${table(["FiO₂","PEEP sugerida"],LOW_PEEP)}<h3>PEEP/FiO₂ alta</h3>${table(["FiO₂","PEEP sugerida"],HIGH_PEEP)}`;}
function getSnapshots(){try{return JSON.parse(localStorage.getItem("respirasense_snapshots")||"[]")}catch{return[]}}
function setSnapshots(v){localStorage.setItem("respirasense_snapshots",JSON.stringify(v))}
function saveSnapshot(){const snaps=getSnapshots(); const snap={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),created_at:new Date().toISOString(),patient_code:el("snapCode").value||"CASO-ANONIMO",setting:el("snapSetting").value,diagnosis:el("snapDiagnosis").value,feedback:el("snapFeedback").value,final_conduct:el("snapConduct").value,tags:el("snapTags").value,data:state,analysis,recommendations}; snaps.unshift(snap); setSnapshots(snaps); renderSnapshots(); alert("Snapshot anônimo salvo neste navegador ✅");}
function renderSnapshots(){const snaps=getSnapshots(); const mean=(key)=>{const vals=snaps.map(s=>key.split('.').reduce((o,k)=>o?.[k],s)).filter(v=>typeof v==='number'&&isFinite(v)); return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}; el("snapshotSummary").innerHTML=[metric("Snapshots",snaps.length,"localStorage"),metric("P/F médio",fmt(mean("analysis.pf_ratio"),0),"histórico"),metric("ROX médio",fmt(mean("analysis.rox_index"),2),"histórico"),metric("ΔP médio",fmt(mean("analysis.mechanics.driving_pressure"),1),"histórico")].join(""); el("snapshotTable").innerHTML=snaps.length?table(["Data","Código","Cenário","Diagnóstico","Suporte","Gravidade","P/F","ROX","ΔP","Feedback","Tags"],snaps.map(s=>[new Date(s.created_at).toLocaleString("pt-BR"),s.patient_code,s.setting,s.diagnosis,s.data.support,s.recommendations?.[0]?.severity||"—",fmt(s.analysis.pf_ratio,0),fmt(s.analysis.rox_index,2),fmt(s.analysis.mechanics.driving_pressure,1),s.feedback,s.tags])):`<div class="info-card">Ainda não há snapshots salvos neste navegador.</div>`;}
function downloadJSON(filename,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); URL.revokeObjectURL(a.href);}
function init(){SUPPORT_OPTIONS.forEach(o=>el("support").insertAdjacentHTML("beforeend",`<option>${o}</option>`)); MODE_OPTIONS.forEach(o=>el("vent_mode").insertAdjacentHTML("beforeend",`<option>${o}</option>`)); Object.keys(DEMO_CASES).forEach(o=>el("demoCase").insertAdjacentHTML("beforeend",`<option>${o}</option>`)); el("demoCase").addEventListener("change",()=>{const c=DEMO_CASES[el("demoCase").value]; Object.entries(c).forEach(([k,v])=>{const node=el(k); if(!node)return; if(node.type==="checkbox") node.checked=!!v; else node.value=v;}); if(el("demoCase").value==="Manual"){} render();}); ids.forEach(id=>{const node=el(id); if(node) node.addEventListener("input",render); if(node) node.addEventListener("change",render);}); ["sim_mode","sim_rr","sim_vt","sim_peep","sim_c","sim_r","sim_ti","sim_pinsp"].forEach(id=>el(id).addEventListener("input",renderSim)); document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".tabpage").forEach(p=>p.classList.remove("active"));btn.classList.add("active");el("tab-"+btn.dataset.tab).classList.add("active"); if(btn.dataset.tab==="sim")setTimeout(renderSim,30);})); el("btnSaveSnapshot").addEventListener("click",saveSnapshot); el("btnDownloadSnapshots").addEventListener("click",()=>downloadJSON("respirasense_snapshots.json",{exported_at:new Date().toISOString(),snapshots:getSnapshots()})); el("btnClearSnapshots").addEventListener("click",()=>{if(confirm("Apagar snapshots locais deste navegador?")){setSnapshots([]);renderSnapshots();}}); el("btnExport").addEventListener("click",()=>downloadJSON("respirasense_snapshot_atual.json",{app:"RespiraSense ICU HTML",exported_at:new Date().toISOString(),data:state,analysis,recommendations})); el("btnPrint").addEventListener("click",()=>window.print()); renderQuick(); renderAsync(); render();}
window.addEventListener("DOMContentLoaded",init); window.addEventListener("resize",()=>setTimeout(renderSim,100));
